// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20231031131239_lols")]
    partial class lols
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("DiscountedPrice")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("PromotionId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("db8f691a-2673-4024-b870-da8528624e15"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Shoes Green",
                            ProductPrice = 620.0,
                            Quantity = 49,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("6c160482-a2fa-4ef4-bf2f-26351e34b814"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt White",
                            ProductPrice = 738.0,
                            Quantity = 55,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("eb72981c-dace-4fb6-80e7-1502c20517ac"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Green",
                            ProductPrice = 727.0,
                            Quantity = 60,
                            Rating = 1
                        },
                        new
                        {
                            ProductId = new Guid("f9a7125a-4e6e-4bc4-87cb-1194af801ce5"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit Green",
                            ProductPrice = 852.0,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("af2e8e44-42a2-496c-bdfd-781acf167792"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Blue",
                            ProductPrice = 243.0,
                            Quantity = 54,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("e46116fd-5bc2-47f9-984b-3adf120ffa86"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt Black",
                            ProductPrice = 751.0,
                            Quantity = 30,
                            Rating = 1
                        },
                        new
                        {
                            ProductId = new Guid("f186a42c-bd9e-48c8-ba16-2850ccb5663b"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Yellow",
                            ProductPrice = 893.0,
                            Quantity = 86,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("d8c734a9-5c50-47ef-a43c-8e5b03686d08"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit Blue",
                            ProductPrice = 489.0,
                            Quantity = 83,
                            Rating = 1
                        },
                        new
                        {
                            ProductId = new Guid("bec4228d-247c-444c-adc5-8382754ed451"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Green",
                            ProductPrice = 539.0,
                            Quantity = 51,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("e7e30caa-6127-4ad2-ac75-cac285a8a960"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Blue",
                            ProductPrice = 365.0,
                            Quantity = 68,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("a429a8b7-2d45-4e9a-9c94-f0ea120971e7"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit Blue",
                            ProductPrice = 552.0,
                            Quantity = 53,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("c77753b8-bd16-4afb-9fd2-3de97787bdbe"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt Red",
                            ProductPrice = 151.0,
                            Quantity = 58,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("1e950ef1-2592-4c7e-8a69-76e00f9cbeef"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Green",
                            ProductPrice = 103.0,
                            Quantity = 99,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("88af9726-85dc-4b73-b9ad-34db7c602a5a"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit White",
                            ProductPrice = 369.0,
                            Quantity = 32,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("3f62d3d0-bb2f-49c1-8188-2510926c4c31"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Blue",
                            ProductPrice = 930.0,
                            Quantity = 61,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("ddc8d365-20fb-4304-bad3-94578c8b95af"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Yellow",
                            ProductPrice = 355.0,
                            Quantity = 16,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("5e3cbeb7-8338-4751-a81e-55384e1d81b0"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Black",
                            ProductPrice = 594.0,
                            Quantity = 64,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("7f433824-0c50-44c9-a035-e20874d2f5da"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Black",
                            ProductPrice = 701.0,
                            Quantity = 57,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("c01279b1-01e6-443f-872c-3690434bec5a"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Yellow",
                            ProductPrice = 489.0,
                            Quantity = 45,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("f79b69ed-bf9e-40cb-9944-4b67ea3ffd75"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Yellow",
                            ProductPrice = 576.0,
                            Quantity = 24,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("41e7aac0-98d5-4249-a3a4-69cdf223395a"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit Blue",
                            ProductPrice = 892.0,
                            Quantity = 49,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("44c02081-a41a-444e-9ff9-78e1e2e03e1f"),
                            ProductDescription = "Description",
                            ProductName = "Cool T-Shirt",
                            ProductPrice = 1000.0,
                            Quantity = 1,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Entities.PromotionEntity", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("DataAccess.Models.Entities.ProductEntity", b =>
                {
                    b.HasOne("DataAccess.Models.Entities.PromotionEntity", "Promotion")
                        .WithMany()
                        .HasForeignKey("PromotionId");

                    b.Navigation("Promotion");
                });
#pragma warning restore 612, 618
        }
    }
}
