// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20231030064622_product entity edit")]
    partial class productentityedit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Entities.PrimaryCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrimaryCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Unisex"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Entities.PrimarySubCategoryEntity", b =>
                {
                    b.Property<int>("PrimaryCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("PrimaryCategoryId", "SubCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("PrimarySubCategory");

                    b.HasData(
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 1
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 1
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            SubCategoryId = 1
                        },
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 2
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 2
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            SubCategoryId = 2
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 3
                        },
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 4
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 4
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            SubCategoryId = 4
                        },
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 5
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 5
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            SubCategoryId = 5
                        },
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 6
                        },
                        new
                        {
                            PrimaryCategoryId = 1,
                            SubCategoryId = 7
                        },
                        new
                        {
                            PrimaryCategoryId = 2,
                            SubCategoryId = 7
                        },
                        new
                        {
                            PrimaryCategoryId = 3,
                            SubCategoryId = 7
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PrimaryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("PrimaryCategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("2fd8d54f-4a97-4331-b5b2-d0b87b3b663a"),
                            PrimaryCategoryId = 3,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Red",
                            ProductPrice = 84.0,
                            Quantity = 79,
                            Rating = 1,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("51839267-0fa5-4ef1-bd1d-177fcaa25917"),
                            PrimaryCategoryId = 3,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Blue",
                            ProductPrice = 352.0,
                            Quantity = 37,
                            Rating = 1,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("ebad6b11-a3f8-41a0-bb10-5f8ea0e24e67"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Black",
                            ProductPrice = 690.0,
                            Quantity = 6,
                            Rating = 1,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("0daa7259-5687-4386-a084-89abb9606271"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Bag Red",
                            ProductPrice = 496.0,
                            Quantity = 17,
                            Rating = 0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            ProductId = new Guid("794191c5-d56d-4b3c-95b2-b7c45bbc9452"),
                            PrimaryCategoryId = 3,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " T-Shirt Yellow",
                            ProductPrice = 419.0,
                            Quantity = 95,
                            Rating = 1,
                            SubCategoryId = 1
                        },
                        new
                        {
                            ProductId = new Guid("468a48da-2033-4c4a-adf4-6c0650c21a71"),
                            PrimaryCategoryId = 3,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Green",
                            ProductPrice = 665.0,
                            Quantity = 72,
                            Rating = 1,
                            SubCategoryId = 2
                        },
                        new
                        {
                            ProductId = new Guid("74d99315-fb8f-4d8d-aedc-475ad76414e8"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Yellow",
                            ProductPrice = 965.0,
                            Quantity = 69,
                            Rating = 3,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("418ac393-8591-4cad-b53e-1b4880521335"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Bag White",
                            ProductPrice = 443.0,
                            Quantity = 90,
                            Rating = 0,
                            SubCategoryId = 5
                        },
                        new
                        {
                            ProductId = new Guid("6f35745c-8195-4fed-b7d8-0a0b8a7a59d5"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Black",
                            ProductPrice = 428.0,
                            Quantity = 5,
                            Rating = 2,
                            SubCategoryId = 2
                        },
                        new
                        {
                            ProductId = new Guid("da9fb991-b219-4f27-a66d-0632c328ad0c"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Red",
                            ProductPrice = 490.0,
                            Quantity = 83,
                            Rating = 2,
                            SubCategoryId = 2
                        },
                        new
                        {
                            ProductId = new Guid("0db079b0-5586-43a7-9219-69e12a88e46e"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Dress Blue",
                            ProductPrice = 693.0,
                            Quantity = 95,
                            Rating = 1,
                            SubCategoryId = 3
                        },
                        new
                        {
                            ProductId = new Guid("34b7a738-e48c-4677-aff8-3b0c5eeb5fb2"),
                            PrimaryCategoryId = 3,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Green",
                            ProductPrice = 872.0,
                            Quantity = 32,
                            Rating = 4,
                            SubCategoryId = 2
                        },
                        new
                        {
                            ProductId = new Guid("15f12228-fef6-4ed7-8441-502eebf2fdc7"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Suit White",
                            ProductPrice = 818.0,
                            Quantity = 9,
                            Rating = 0,
                            SubCategoryId = 6
                        },
                        new
                        {
                            ProductId = new Guid("362cdaa4-2803-4c32-99fe-451d7714093d"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Suit Blue",
                            ProductPrice = 248.0,
                            Quantity = 90,
                            Rating = 4,
                            SubCategoryId = 6
                        },
                        new
                        {
                            ProductId = new Guid("fd7a01a8-f607-45e7-ab04-90ca7ba701a1"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Yellow",
                            ProductPrice = 245.0,
                            Quantity = 22,
                            Rating = 0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("3e6c6d67-5e30-4965-93a3-712da506143c"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Shoes Black",
                            ProductPrice = 593.0,
                            Quantity = 44,
                            Rating = 4,
                            SubCategoryId = 4
                        },
                        new
                        {
                            ProductId = new Guid("d7de5cb2-f019-4133-89de-24b696f04932"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Dress White",
                            ProductPrice = 194.0,
                            Quantity = 4,
                            Rating = 3,
                            SubCategoryId = 3
                        },
                        new
                        {
                            ProductId = new Guid("325ebfc2-ef90-4feb-bbfe-e85ca76b30bb"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Green",
                            ProductPrice = 258.0,
                            Quantity = 1,
                            Rating = 0,
                            SubCategoryId = 2
                        },
                        new
                        {
                            ProductId = new Guid("9e27eb80-db90-481c-a1b6-760b8ee1456c"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Suit Yellow",
                            ProductPrice = 128.0,
                            Quantity = 17,
                            Rating = 3,
                            SubCategoryId = 6
                        },
                        new
                        {
                            ProductId = new Guid("17875954-9eb2-4e9e-8d22-d17f9bd1efd4"),
                            PrimaryCategoryId = 2,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Dress Yellow",
                            ProductPrice = 428.0,
                            Quantity = 0,
                            Rating = 2,
                            SubCategoryId = 3
                        },
                        new
                        {
                            ProductId = new Guid("aae98eee-b2a0-4af8-8531-14afa388adda"),
                            PrimaryCategoryId = 1,
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = " Pants Blue",
                            ProductPrice = 473.0,
                            Quantity = 23,
                            Rating = 3,
                            SubCategoryId = 2
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Entities.SubCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bags"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Suits"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.Entities.PrimarySubCategoryEntity", b =>
                {
                    b.HasOne("DataAccess.Models.Entities.PrimaryCategoryEntity", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Entities.SubCategoryEntity", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCategory");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("DataAccess.Models.Entities.ProductEntity", b =>
                {
                    b.HasOne("DataAccess.Models.Entities.PrimaryCategoryEntity", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Models.Entities.SubCategoryEntity", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrimaryCategory");

                    b.Navigation("SubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
