// <auto-generated />
using System;
using DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(LocalContext))]
    partial class LocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("919d5dd1-d60b-49b3-a595-bdd04df9e59d"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Red",
                            ProductPrice = 726.0,
                            Quantity = 86,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("b1764dce-6cc4-468f-9b13-db6d3888c681"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit White",
                            ProductPrice = 556.0,
                            Quantity = 27,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("2c186442-9570-4ff8-a5b7-dd7417432070"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag White",
                            ProductPrice = 886.0,
                            Quantity = 46,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("56c68487-4dba-4605-89ca-49b47b67691b"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Blue",
                            ProductPrice = 478.0,
                            Quantity = 24,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("72e3a0c3-4a27-47f6-95ec-8f69fa0a755b"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit Blue",
                            ProductPrice = 66.0,
                            Quantity = 15,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("a4032ae2-568e-41a4-917d-ce7cef16831d"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Shoes Blue",
                            ProductPrice = 278.0,
                            Quantity = 44,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("a114f370-726e-4340-b802-90ebe688b0af"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Suit White",
                            ProductPrice = 870.0,
                            Quantity = 84,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("1e200ca3-0718-40aa-9e8b-8f6aff3f28a1"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Red",
                            ProductPrice = 535.0,
                            Quantity = 74,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("cea3492d-64d7-495f-ae24-392a31c3a638"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Green",
                            ProductPrice = 107.0,
                            Quantity = 2,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("beb3e827-93ad-4ff3-b4e0-b2f4c2c74d23"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt Black",
                            ProductPrice = 467.0,
                            Quantity = 98,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("8015425a-77d9-4527-a7c8-77cbd87167e4"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt Black",
                            ProductPrice = 852.0,
                            Quantity = 36,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("f7da9290-b0ac-4469-8d98-b0bf14f1e99a"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Bag Green",
                            ProductPrice = 354.0,
                            Quantity = 65,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("3dd92e82-aa40-4c73-9b2c-f86b50010739"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "T-Shirt Blue",
                            ProductPrice = 383.0,
                            Quantity = 14,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("a9f32e7a-bc63-4a9a-b0c3-0128a81c04b2"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Blue",
                            ProductPrice = 184.0,
                            Quantity = 19,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("c47dca12-cfe2-42f8-ba60-bd72165c147c"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Shoes Black",
                            ProductPrice = 341.0,
                            Quantity = 1,
                            Rating = 1
                        },
                        new
                        {
                            ProductId = new Guid("d8a78021-16d6-4449-907f-bcfe109db100"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress White",
                            ProductPrice = 637.0,
                            Quantity = 47,
                            Rating = 3
                        },
                        new
                        {
                            ProductId = new Guid("cc492cac-3c4b-4be0-8ed2-a3cbf5d7d926"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress White",
                            ProductPrice = 123.0,
                            Quantity = 10,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("10d76a00-e0d2-48a6-b34b-3ae8cd88f924"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Dress Blue",
                            ProductPrice = 843.0,
                            Quantity = 57,
                            Rating = 2
                        },
                        new
                        {
                            ProductId = new Guid("337b7676-d607-4c6e-ae01-ded65008db4d"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Blue",
                            ProductPrice = 404.0,
                            Quantity = 34,
                            Rating = 0
                        },
                        new
                        {
                            ProductId = new Guid("51f6ddc4-8e1a-4bb2-b390-149776a12ec2"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Pants Green",
                            ProductPrice = 471.0,
                            Quantity = 10,
                            Rating = 4
                        },
                        new
                        {
                            ProductId = new Guid("5014b035-39fa-4ef9-b3a4-419a8daf0958"),
                            ProductDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum, libero non rhoncus cursus, dolor libero accumsan ex, vel blandit elit neque quis ante. Morbi magna ex, fringilla id vehicula at, molestie id turpis. Duis bibendum ultrices sem, nec gravida enim tempor at. Praesent ac nulla tellus. Sed sed massa. ",
                            ProductName = "Shoes Red",
                            ProductPrice = 321.0,
                            Quantity = 17,
                            Rating = 1
                        },
                        new
                        {
                            ProductId = new Guid("032a2adf-0e20-48f7-83d1-ae560c4355ac"),
                            ProductDescription = "Description",
                            ProductName = "Cool T-Shirt",
                            ProductPrice = 1000.0,
                            Quantity = 1,
                            Rating = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
